### ISSUE TITLE
Support for 1.21

### ISSUE THREAD

**Issue by Kapyyyy** [imDMK/SpentTime#53]
I'm running a purpur server on 1.21 and the commands don't work. Seems like this plugin needs updating.

Server console outputs this:

[13:55:20 ERROR]: Error occurred while enabling SpentTime v1.0.6 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at SpentTime v1.0.6.jar/com.github.imdmk.spenttime.gui.settings.GuiItemSettings.<init>(GuiItemSettings.java:49) ~[SpentTime v1.0.6.jar:?]
        at SpentTime v1.0.6.jar/com.github.imdmk.spenttime.gui.settings.GuiSettings.<init>(GuiSettings.java:29) ~[SpentTime v1.0.6.jar:?]
        at SpentTime v1.0.6.jar/com.github.imdmk.spenttime.configuration.implementation.PluginConfiguration.<init>(PluginConfiguration.java:36) ~[SpentTime v1.0.6.jar:?]
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
        at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
        at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:304) ~[?:?]
        at java.base/java.lang.Class.newInstance(Class.java:725) ~[?:?]
        at SpentTime v1.0.6.jar/com.github.imdmk.spenttime.lib.eu.okaeri.configs.ConfigManager.create(ConfigManager.java:22) ~[SpentTime v1.0.6.jar:?]
        at SpentTime v1.0.6.jar/com.github.imdmk.spenttime.configuration.ConfigurationFactory.create(ConfigurationFactory.java:28) ~[SpentTime v1.0.6.jar:?]
        at SpentTime v1.0.6.jar/com.github.imdmk.spenttime.SpentTime.<init>(SpentTime.java:93) ~[SpentTime v1.0.6.jar:?]
        at SpentTime v1.0.6.jar/com.github.imdmk.spenttime.SpentTimePlugin.onEnable(SpentTimePlugin.java:11) ~[SpentTime v1.0.6.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[purpur-1.21.jar:1.21-2265-8f0f20d]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.21.jar:1.21-2265-8f0f20d]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:643) ~[purpur-1.21.jar:1.21-2265-8f0f20d]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:592) ~[purpur-1.21.jar:1.21-2265-8f0f20d]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:756) ~[purpur-1.21.jar:1.21-2265-8f0f20d]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:518) ~[purpur-1.21.jar:1.21-2265-8f0f20d]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:361) ~[purpur-1.21.jar:1.21-2265-8f0f20d]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1225) ~[purpur-1.21.jar:1.21-2265-8f0f20d]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.jar:1.21-2265-8f0f20d]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: com.github.imdmk.spenttime.lib.dev.triumphteam.gui.components.exception.GuiException: Could not retrieve displayName nor lore field for ItemBuilder.
        at SpentTime v1.0.6.jar/com.github.imdmk.spenttime.lib.dev.triumphteam.gui.builder.item.BaseItemBuilder.<clinit>(BaseItemBuilder.java:86) ~[SpentTime v1.0.6.jar:?]
        ... 24 more
[13:55:20 INFO]: [SpentTime] Disabling SpentTime v1.0.6

**Comment by imDMK** [comment]
The issue has been resolved. Plugin works on latest versions. 
Thanks for the issue!
Regards.
